### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hedgehog-genki** [hedgehog-genki/furima-35942#11]
## 自身のフリマアプリのURL
https://furima-35942.herokuapp.com/

## Basic認証のIDとパスワード
ID:admin
Pass:1111

## 出品者用のメールアドレスとパスワード
メールアドレス:test@gmail.com
Pass:abc1234

## 購入者用のメールアドレスとパスワード
メールアドレス:test@yahoo.co.jp
Pass:abc1234

**Comment by snkw-works** [comment]
@hedgehog-genki さん、大変お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

 [修正依頼箇所]
- [x] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できるよう修正しましょう**
「商品の編集」ボタンを押すと、トップページに遷移してしまいます。

- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができるよう修正しましょう**
正しいクレジットカード情報を入力しても、画像のエラーメッセージが表示され購入ができない状態です。
【入力したカード情報】
・カード番号：4242424242424242
・有効期限：3月 23年
・セキュリティコード：123
<img width="747" alt="スクリーンショット 2021-06-19 14 22 49" src="https://user-images.githubusercontent.com/54050089/122694224-ae2c1d80-d277-11eb-9c74-67a8c91b2305.png">

※購入機能と購入後に関する項目に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@hedgehog-genki さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/122699475-74addf00-d284-11eb-967d-12614a085441.png)

**Comment by hedgehog-genki** [comment]
ありがとうございます。
